projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://enrol-Publi-15DTFMVR8KX05-1492607005.ap-northeast-1.elb.amazonaws.com/prisma-enroll/staging
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      # codegen:
      #   - generator: prisma-binding
      #     language: javascript
      #     output:
      #       binding: src/generated/prisma.js
